# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_pb2 as data__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeHealthReportForUser = channel.unary_unary(
                '/health.HealthService/AnalyzeHealthReportForUser',
                request_serializer=data__pb2.AnalyzeHealthReportRequest.SerializeToString,
                response_deserializer=data__pb2.UserHealthAnalysisResponse.FromString,
                _registered_method=True)
        self.AnalyzeHealthReportForInsurer = channel.unary_unary(
                '/health.HealthService/AnalyzeHealthReportForInsurer',
                request_serializer=data__pb2.AnalyzeHealthReportRequest.SerializeToString,
                response_deserializer=data__pb2.InsurerHealthAnalysisResponse.FromString,
                _registered_method=True)
        self.ParseDocument = channel.unary_unary(
                '/health.HealthService/ParseDocument',
                request_serializer=data__pb2.ParseDocumentRequest.SerializeToString,
                response_deserializer=data__pb2.ParseDocumentResponse.FromString,
                _registered_method=True)
        self.GetHealthAnalysis = channel.unary_unary(
                '/health.HealthService/GetHealthAnalysis',
                request_serializer=data__pb2.AnalyzeReportRequest.SerializeToString,
                response_deserializer=data__pb2.HealthAnalysisResponse.FromString,
                _registered_method=True)
        self.UploadReport = channel.unary_unary(
                '/health.HealthService/UploadReport',
                request_serializer=data__pb2.UploadReportRequest.SerializeToString,
                response_deserializer=data__pb2.UploadReportResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/health.HealthService/Login',
                request_serializer=data__pb2.LoginRequest.SerializeToString,
                response_deserializer=data__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RegisterUser = channel.unary_unary(
                '/health.HealthService/RegisterUser',
                request_serializer=data__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=data__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.RegisterInsurer = channel.unary_unary(
                '/health.HealthService/RegisterInsurer',
                request_serializer=data__pb2.RegisterInsurerRequest.SerializeToString,
                response_deserializer=data__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.ListMyReportMeta = channel.unary_unary(
                '/health.HealthService/ListMyReportMeta',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=data__pb2.ListMyReportMetaResponse.FromString,
                _registered_method=True)
        self.ReadMyReport = channel.unary_unary(
                '/health.HealthService/ReadMyReport',
                request_serializer=data__pb2.ReadMyReportRequest.SerializeToString,
                response_deserializer=data__pb2.ReadMyReportResponse.FromString,
                _registered_method=True)
        self.ListMyAuthorizedTickets = channel.unary_unary(
                '/health.HealthService/ListMyAuthorizedTickets',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=data__pb2.ListAuthorizedTicketsResponse.FromString,
                _registered_method=True)
        self.RequestAccess = channel.unary_unary(
                '/health.HealthService/RequestAccess',
                request_serializer=data__pb2.RequestAccessRequest.SerializeToString,
                response_deserializer=data__pb2.RequestAccessResponse.FromString,
                _registered_method=True)
        self.ListAccessRequests = channel.unary_unary(
                '/health.HealthService/ListAccessRequests',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=data__pb2.ListAccessRequestsResponse.FromString,
                _registered_method=True)
        self.ApproveAccessRequest = channel.unary_unary(
                '/health.HealthService/ApproveAccessRequest',
                request_serializer=data__pb2.ApproveAccessRequestRequest.SerializeToString,
                response_deserializer=data__pb2.ApproveAccessRequestResponse.FromString,
                _registered_method=True)
        self.RejectAccessRequest = channel.unary_unary(
                '/health.HealthService/RejectAccessRequest',
                request_serializer=data__pb2.RejectAccessRequestRequest.SerializeToString,
                response_deserializer=data__pb2.RejectAccessRequestResponse.FromString,
                _registered_method=True)
        self.ListAuthorizedReports = channel.unary_unary(
                '/health.HealthService/ListAuthorizedReports',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=data__pb2.ListAuthorizedReportsResponse.FromString,
                _registered_method=True)
        self.ListReportMetaByPatientID = channel.unary_unary(
                '/health.HealthService/ListReportMetaByPatientID',
                request_serializer=data__pb2.PatientIDRequest.SerializeToString,
                response_deserializer=data__pb2.ListReportMetaResponse.FromString,
                _registered_method=True)
        self.ViewAuthorizedReport = channel.unary_unary(
                '/health.HealthService/ViewAuthorizedReport',
                request_serializer=data__pb2.ViewAuthorizedReportRequest.SerializeToString,
                response_deserializer=data__pb2.ViewAuthorizedReportResponse.FromString,
                _registered_method=True)
        self.ListMyAccessRequests = channel.unary_unary(
                '/health.HealthService/ListMyAccessRequests',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=data__pb2.ListMyAccessRequestsResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeHealthReportForUser(self, request, context):
        """========================
        健康分析功能（Python Backend 提供）
        ========================
        這些方法在 Python backend 中實現
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeHealthReportForInsurer(self, request, context):
        """這些方法在 Python backend 中實現
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseDocument(self, request, context):
        """解析文件（PDF/Word）並轉換為標準 JSON
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealthAnalysis(self, request, context):
        """前端請求健檢資料分析（通過報告 ID）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadReport(self, request, context):
        """========================
        Hyperledger Fabric 功能（Go Server 提供）
        ========================

        健檢中心上傳報告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """登入
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """用戶註冊
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterInsurer(self, request, context):
        """保險業者註冊
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyReportMeta(self, request, context):
        """用戶讀取自己的報告 meta (只有metadata，不包含內容)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMyReport(self, request, context):
        """用戶讀取自己的完整報告內容
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyAuthorizedTickets(self, request, context):
        """用戶讀取授權紀錄
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAccess(self, request, context):
        """請求授權
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessRequests(self, request, context):
        """請求授權列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAccessRequest(self, request, context):
        """接受授權
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectAccessRequest(self, request, context):
        """拒絕授權
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuthorizedReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReportMetaByPatientID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewAuthorizedReport(self, request, context):
        """保險業者讀授權報告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyAccessRequests(self, request, context):
        """保險業者查看自己發出的授權請求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeHealthReportForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeHealthReportForUser,
                    request_deserializer=data__pb2.AnalyzeHealthReportRequest.FromString,
                    response_serializer=data__pb2.UserHealthAnalysisResponse.SerializeToString,
            ),
            'AnalyzeHealthReportForInsurer': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeHealthReportForInsurer,
                    request_deserializer=data__pb2.AnalyzeHealthReportRequest.FromString,
                    response_serializer=data__pb2.InsurerHealthAnalysisResponse.SerializeToString,
            ),
            'ParseDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=data__pb2.ParseDocumentRequest.FromString,
                    response_serializer=data__pb2.ParseDocumentResponse.SerializeToString,
            ),
            'GetHealthAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthAnalysis,
                    request_deserializer=data__pb2.AnalyzeReportRequest.FromString,
                    response_serializer=data__pb2.HealthAnalysisResponse.SerializeToString,
            ),
            'UploadReport': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadReport,
                    request_deserializer=data__pb2.UploadReportRequest.FromString,
                    response_serializer=data__pb2.UploadReportResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=data__pb2.LoginRequest.FromString,
                    response_serializer=data__pb2.LoginResponse.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=data__pb2.RegisterUserRequest.FromString,
                    response_serializer=data__pb2.RegisterResponse.SerializeToString,
            ),
            'RegisterInsurer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterInsurer,
                    request_deserializer=data__pb2.RegisterInsurerRequest.FromString,
                    response_serializer=data__pb2.RegisterResponse.SerializeToString,
            ),
            'ListMyReportMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyReportMeta,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=data__pb2.ListMyReportMetaResponse.SerializeToString,
            ),
            'ReadMyReport': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMyReport,
                    request_deserializer=data__pb2.ReadMyReportRequest.FromString,
                    response_serializer=data__pb2.ReadMyReportResponse.SerializeToString,
            ),
            'ListMyAuthorizedTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyAuthorizedTickets,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=data__pb2.ListAuthorizedTicketsResponse.SerializeToString,
            ),
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=data__pb2.RequestAccessRequest.FromString,
                    response_serializer=data__pb2.RequestAccessResponse.SerializeToString,
            ),
            'ListAccessRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessRequests,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=data__pb2.ListAccessRequestsResponse.SerializeToString,
            ),
            'ApproveAccessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAccessRequest,
                    request_deserializer=data__pb2.ApproveAccessRequestRequest.FromString,
                    response_serializer=data__pb2.ApproveAccessRequestResponse.SerializeToString,
            ),
            'RejectAccessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectAccessRequest,
                    request_deserializer=data__pb2.RejectAccessRequestRequest.FromString,
                    response_serializer=data__pb2.RejectAccessRequestResponse.SerializeToString,
            ),
            'ListAuthorizedReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuthorizedReports,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=data__pb2.ListAuthorizedReportsResponse.SerializeToString,
            ),
            'ListReportMetaByPatientID': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReportMetaByPatientID,
                    request_deserializer=data__pb2.PatientIDRequest.FromString,
                    response_serializer=data__pb2.ListReportMetaResponse.SerializeToString,
            ),
            'ViewAuthorizedReport': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewAuthorizedReport,
                    request_deserializer=data__pb2.ViewAuthorizedReportRequest.FromString,
                    response_serializer=data__pb2.ViewAuthorizedReportResponse.SerializeToString,
            ),
            'ListMyAccessRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyAccessRequests,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=data__pb2.ListMyAccessRequestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'health.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('health.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeHealthReportForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/AnalyzeHealthReportForUser',
            data__pb2.AnalyzeHealthReportRequest.SerializeToString,
            data__pb2.UserHealthAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeHealthReportForInsurer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/AnalyzeHealthReportForInsurer',
            data__pb2.AnalyzeHealthReportRequest.SerializeToString,
            data__pb2.InsurerHealthAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ParseDocument',
            data__pb2.ParseDocumentRequest.SerializeToString,
            data__pb2.ParseDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealthAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/GetHealthAnalysis',
            data__pb2.AnalyzeReportRequest.SerializeToString,
            data__pb2.HealthAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/UploadReport',
            data__pb2.UploadReportRequest.SerializeToString,
            data__pb2.UploadReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/Login',
            data__pb2.LoginRequest.SerializeToString,
            data__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/RegisterUser',
            data__pb2.RegisterUserRequest.SerializeToString,
            data__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterInsurer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/RegisterInsurer',
            data__pb2.RegisterInsurerRequest.SerializeToString,
            data__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyReportMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ListMyReportMeta',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            data__pb2.ListMyReportMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMyReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ReadMyReport',
            data__pb2.ReadMyReportRequest.SerializeToString,
            data__pb2.ReadMyReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyAuthorizedTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ListMyAuthorizedTickets',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            data__pb2.ListAuthorizedTicketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/RequestAccess',
            data__pb2.RequestAccessRequest.SerializeToString,
            data__pb2.RequestAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccessRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ListAccessRequests',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            data__pb2.ListAccessRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAccessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ApproveAccessRequest',
            data__pb2.ApproveAccessRequestRequest.SerializeToString,
            data__pb2.ApproveAccessRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectAccessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/RejectAccessRequest',
            data__pb2.RejectAccessRequestRequest.SerializeToString,
            data__pb2.RejectAccessRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuthorizedReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ListAuthorizedReports',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            data__pb2.ListAuthorizedReportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReportMetaByPatientID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ListReportMetaByPatientID',
            data__pb2.PatientIDRequest.SerializeToString,
            data__pb2.ListReportMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewAuthorizedReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ViewAuthorizedReport',
            data__pb2.ViewAuthorizedReportRequest.SerializeToString,
            data__pb2.ViewAuthorizedReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyAccessRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/ListMyAccessRequests',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            data__pb2.ListMyAccessRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
