# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthServiceStub(object):
    """import "google/api/annotations.proto";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeHealthReportForUser = channel.unary_unary(
                '/health.HealthService/AnalyzeHealthReportForUser',
                request_serializer=data__pb2.AnalyzeHealthReportRequest.SerializeToString,
                response_deserializer=data__pb2.UserHealthAnalysisResponse.FromString,
                _registered_method=True)
        self.AnalyzeHealthReportForInsurer = channel.unary_unary(
                '/health.HealthService/AnalyzeHealthReportForInsurer',
                request_serializer=data__pb2.AnalyzeHealthReportRequest.SerializeToString,
                response_deserializer=data__pb2.InsurerHealthAnalysisResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """import "google/api/annotations.proto";

    """

    def AnalyzeHealthReportForUser(self, request, context):
        """option (google.api.http) = {
        post: "/v1/analyze/user"
        body: "*"
        };
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeHealthReportForInsurer(self, request, context):
        """option (google.api.http) = {
        post: "/v1/analyze/insurer"
        body: "*"
        };
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeHealthReportForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeHealthReportForUser,
                    request_deserializer=data__pb2.AnalyzeHealthReportRequest.FromString,
                    response_serializer=data__pb2.UserHealthAnalysisResponse.SerializeToString,
            ),
            'AnalyzeHealthReportForInsurer': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeHealthReportForInsurer,
                    request_deserializer=data__pb2.AnalyzeHealthReportRequest.FromString,
                    response_serializer=data__pb2.InsurerHealthAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'health.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('health.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """import "google/api/annotations.proto";

    """

    @staticmethod
    def AnalyzeHealthReportForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/AnalyzeHealthReportForUser',
            data__pb2.AnalyzeHealthReportRequest.SerializeToString,
            data__pb2.UserHealthAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeHealthReportForInsurer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthService/AnalyzeHealthReportForInsurer',
            data__pb2.AnalyzeHealthReportRequest.SerializeToString,
            data__pb2.InsurerHealthAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
