// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/data.proto

package health

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessRequestStatus int32

const (
	AccessRequestStatus_PENDING  AccessRequestStatus = 0
	AccessRequestStatus_APPROVED AccessRequestStatus = 1
	AccessRequestStatus_REJECTED AccessRequestStatus = 2
)

// Enum value maps for AccessRequestStatus.
var (
	AccessRequestStatus_name = map[int32]string{
		0: "PENDING",
		1: "APPROVED",
		2: "REJECTED",
	}
	AccessRequestStatus_value = map[string]int32{
		"PENDING":  0,
		"APPROVED": 1,
		"REJECTED": 2,
	}
)

func (x AccessRequestStatus) Enum() *AccessRequestStatus {
	p := new(AccessRequestStatus)
	*p = x
	return p
}

func (x AccessRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_proto_enumTypes[0].Descriptor()
}

func (AccessRequestStatus) Type() protoreflect.EnumType {
	return &file_proto_data_proto_enumTypes[0]
}

func (x AccessRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRequestStatus.Descriptor instead.
func (AccessRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

type UploadReportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReportId        string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TestResultsJson string                 `protobuf:"bytes,3,opt,name=test_results_json,json=testResultsJson,proto3" json:"test_results_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadReportRequest) Reset() {
	*x = UploadReportRequest{}
	mi := &file_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReportRequest) ProtoMessage() {}

func (x *UploadReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReportRequest.ProtoReflect.Descriptor instead.
func (*UploadReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *UploadReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *UploadReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadReportRequest) GetTestResultsJson() string {
	if x != nil {
		return x.TestResultsJson
	}
	return ""
}

type UploadReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReportResponse) Reset() {
	*x = UploadReportResponse{}
	mi := &file_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReportResponse) ProtoMessage() {}

func (x *UploadReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReportResponse.ProtoReflect.Descriptor instead.
func (*UploadReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *UploadReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClaimReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimReportRequest) Reset() {
	*x = ClaimReportRequest{}
	mi := &file_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimReportRequest) ProtoMessage() {}

func (x *ClaimReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimReportRequest.ProtoReflect.Descriptor instead.
func (*ClaimReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ClaimReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimReportResponse) Reset() {
	*x = ClaimReportResponse{}
	mi := &file_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimReportResponse) ProtoMessage() {}

func (x *ClaimReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimReportResponse.ProtoReflect.Descriptor instead.
func (*ClaimReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReportRequest) Reset() {
	*x = ReadReportRequest{}
	mi := &file_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReportRequest) ProtoMessage() {}

func (x *ReadReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReportRequest.ProtoReflect.Descriptor instead.
func (*ReadReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *ReadReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ReadReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReportContent string                 `protobuf:"bytes,2,opt,name=report_content,json=reportContent,proto3" json:"report_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReportResponse) Reset() {
	*x = ReadReportResponse{}
	mi := &file_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReportResponse) ProtoMessage() {}

func (x *ReadReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReportResponse.ProtoReflect.Descriptor instead.
func (*ReadReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *ReadReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadReportResponse) GetReportContent() string {
	if x != nil {
		return x.ReportContent
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_proto_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterInsurerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsurerId     string                 `protobuf:"bytes,1,opt,name=insurer_id,json=insurerId,proto3" json:"insurer_id,omitempty"` // 例如: CATHAY-01
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CompanyName   string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	ContactPerson string                 `protobuf:"bytes,4,opt,name=contact_person,json=contactPerson,proto3" json:"contact_person,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInsurerRequest) Reset() {
	*x = RegisterInsurerRequest{}
	mi := &file_proto_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInsurerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInsurerRequest) ProtoMessage() {}

func (x *RegisterInsurerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInsurerRequest.ProtoReflect.Descriptor instead.
func (*RegisterInsurerRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterInsurerRequest) GetInsurerId() string {
	if x != nil {
		return x.InsurerId
	}
	return ""
}

func (x *RegisterInsurerRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterInsurerRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *RegisterInsurerRequest) GetContactPerson() string {
	if x != nil {
		return x.ContactPerson
	}
	return ""
}

func (x *RegisterInsurerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterInsurerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ClinicId      string                 `protobuf:"bytes,2,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	PatientHash   string                 `protobuf:"bytes,3,opt,name=patient_hash,json=patientHash,proto3" json:"patient_hash,omitempty"`
	ResultJson    string                 `protobuf:"bytes,4,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_proto_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{11}
}

func (x *Report) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *Report) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *Report) GetPatientHash() string {
	if x != nil {
		return x.PatientHash
	}
	return ""
}

func (x *Report) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *Report) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListMyReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyReportsResponse) Reset() {
	*x = ListMyReportsResponse{}
	mi := &file_proto_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyReportsResponse) ProtoMessage() {}

func (x *ListMyReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyReportsResponse.ProtoReflect.Descriptor instead.
func (*ListMyReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{12}
}

func (x *ListMyReportsResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

// 🔵 保險業者送出授權申請
type RequestAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Expiry        int64                  `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"` // Unix 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccessRequest) Reset() {
	*x = RequestAccessRequest{}
	mi := &file_proto_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccessRequest) ProtoMessage() {}

func (x *RequestAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccessRequest.ProtoReflect.Descriptor instead.
func (*RequestAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{13}
}

func (x *RequestAccessRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *RequestAccessRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RequestAccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RequestAccessRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type RequestAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccessResponse) Reset() {
	*x = RequestAccessResponse{}
	mi := &file_proto_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccessResponse) ProtoMessage() {}

func (x *RequestAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccessResponse.ProtoReflect.Descriptor instead.
func (*RequestAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{14}
}

func (x *RequestAccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestAccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 🟢 病患查詢自己的待審申請
type AccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	PatientHash   string                 `protobuf:"bytes,3,opt,name=patient_hash,json=patientHash,proto3" json:"patient_hash,omitempty"`
	RequesterHash string                 `protobuf:"bytes,4,opt,name=requester_hash,json=requesterHash,proto3" json:"requester_hash,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   int64                  `protobuf:"varint,6,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	Expiry        int64                  `protobuf:"varint,7,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	RequesterName string                 `protobuf:"bytes,9,opt,name=requester_name,json=requesterName,proto3" json:"requester_name,omitempty"`
	CompanyName   string                 `protobuf:"bytes,10,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_proto_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{15}
}

func (x *AccessRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AccessRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AccessRequest) GetPatientHash() string {
	if x != nil {
		return x.PatientHash
	}
	return ""
}

func (x *AccessRequest) GetRequesterHash() string {
	if x != nil {
		return x.RequesterHash
	}
	return ""
}

func (x *AccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AccessRequest) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *AccessRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *AccessRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccessRequest) GetRequesterName() string {
	if x != nil {
		return x.RequesterName
	}
	return ""
}

func (x *AccessRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type ListAccessRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*AccessRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessRequestsResponse) Reset() {
	*x = ListAccessRequestsResponse{}
	mi := &file_proto_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessRequestsResponse) ProtoMessage() {}

func (x *ListAccessRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListAccessRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{16}
}

func (x *ListAccessRequestsResponse) GetRequests() []*AccessRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// 🟡 病患點同意授權
type ApproveAccessRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAccessRequestRequest) Reset() {
	*x = ApproveAccessRequestRequest{}
	mi := &file_proto_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAccessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAccessRequestRequest) ProtoMessage() {}

func (x *ApproveAccessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAccessRequestRequest.ProtoReflect.Descriptor instead.
func (*ApproveAccessRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{17}
}

func (x *ApproveAccessRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApproveAccessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAccessRequestResponse) Reset() {
	*x = ApproveAccessRequestResponse{}
	mi := &file_proto_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAccessRequestResponse) ProtoMessage() {}

func (x *ApproveAccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAccessRequestResponse.ProtoReflect.Descriptor instead.
func (*ApproveAccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{18}
}

func (x *ApproveAccessRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApproveAccessRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 🔴 病患拒絕授權
type RejectAccessRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectAccessRequestRequest) Reset() {
	*x = RejectAccessRequestRequest{}
	mi := &file_proto_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectAccessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectAccessRequestRequest) ProtoMessage() {}

func (x *RejectAccessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectAccessRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectAccessRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{19}
}

func (x *RejectAccessRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RejectAccessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectAccessRequestResponse) Reset() {
	*x = RejectAccessRequestResponse{}
	mi := &file_proto_data_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectAccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectAccessRequestResponse) ProtoMessage() {}

func (x *RejectAccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectAccessRequestResponse.ProtoReflect.Descriptor instead.
func (*RejectAccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{20}
}

func (x *RejectAccessRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RejectAccessRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InsurerDashboardStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalAuthorized int32                  `protobuf:"varint,1,opt,name=total_authorized,json=totalAuthorized,proto3" json:"total_authorized,omitempty"`
	PendingRequests int32                  `protobuf:"varint,2,opt,name=pending_requests,json=pendingRequests,proto3" json:"pending_requests,omitempty"`
	TotalPatients   int32                  `protobuf:"varint,3,opt,name=total_patients,json=totalPatients,proto3" json:"total_patients,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsurerDashboardStatsResponse) Reset() {
	*x = InsurerDashboardStatsResponse{}
	mi := &file_proto_data_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsurerDashboardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsurerDashboardStatsResponse) ProtoMessage() {}

func (x *InsurerDashboardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsurerDashboardStatsResponse.ProtoReflect.Descriptor instead.
func (*InsurerDashboardStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{21}
}

func (x *InsurerDashboardStatsResponse) GetTotalAuthorized() int32 {
	if x != nil {
		return x.TotalAuthorized
	}
	return 0
}

func (x *InsurerDashboardStatsResponse) GetPendingRequests() int32 {
	if x != nil {
		return x.PendingRequests
	}
	return 0
}

func (x *InsurerDashboardStatsResponse) GetTotalPatients() int32 {
	if x != nil {
		return x.TotalPatients
	}
	return 0
}

type AuthorizedReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Expiry        string                 `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedReport) Reset() {
	*x = AuthorizedReport{}
	mi := &file_proto_data_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedReport) ProtoMessage() {}

func (x *AuthorizedReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedReport.ProtoReflect.Descriptor instead.
func (*AuthorizedReport) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{22}
}

func (x *AuthorizedReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AuthorizedReport) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AuthorizedReport) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AuthorizedReport) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

type ListAuthorizedReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*AuthorizedReport    `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorizedReportsResponse) Reset() {
	*x = ListAuthorizedReportsResponse{}
	mi := &file_proto_data_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorizedReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorizedReportsResponse) ProtoMessage() {}

func (x *ListAuthorizedReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorizedReportsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorizedReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{23}
}

func (x *ListAuthorizedReportsResponse) GetReports() []*AuthorizedReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type PatientIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientIDRequest) Reset() {
	*x = PatientIDRequest{}
	mi := &file_proto_data_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientIDRequest) ProtoMessage() {}

func (x *PatientIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientIDRequest.ProtoReflect.Descriptor instead.
func (*PatientIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{24}
}

func (x *PatientIDRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type ReportMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ClinicId      string                 `protobuf:"bytes,2,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMeta) Reset() {
	*x = ReportMeta{}
	mi := &file_proto_data_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMeta) ProtoMessage() {}

func (x *ReportMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMeta.ProtoReflect.Descriptor instead.
func (*ReportMeta) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{25}
}

func (x *ReportMeta) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportMeta) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *ReportMeta) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListReportMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ReportMeta          `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportMetaResponse) Reset() {
	*x = ListReportMetaResponse{}
	mi := &file_proto_data_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportMetaResponse) ProtoMessage() {}

func (x *ListReportMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportMetaResponse.ProtoReflect.Descriptor instead.
func (*ListReportMetaResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{26}
}

func (x *ListReportMetaResponse) GetReports() []*ReportMeta {
	if x != nil {
		return x.Reports
	}
	return nil
}

type ViewAuthorizedReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAuthorizedReportRequest) Reset() {
	*x = ViewAuthorizedReportRequest{}
	mi := &file_proto_data_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAuthorizedReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAuthorizedReportRequest) ProtoMessage() {}

func (x *ViewAuthorizedReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAuthorizedReportRequest.ProtoReflect.Descriptor instead.
func (*ViewAuthorizedReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{27}
}

func (x *ViewAuthorizedReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ViewAuthorizedReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ViewAuthorizedReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // 報告全文或格式化內容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAuthorizedReportResponse) Reset() {
	*x = ViewAuthorizedReportResponse{}
	mi := &file_proto_data_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAuthorizedReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAuthorizedReportResponse) ProtoMessage() {}

func (x *ViewAuthorizedReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAuthorizedReportResponse.ProtoReflect.Descriptor instead.
func (*ViewAuthorizedReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{28}
}

func (x *ViewAuthorizedReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ViewAuthorizedReportResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

var File_proto_data_proto protoreflect.FileDescriptor

const file_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x10proto/data.proto\x12\x06health\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"w\n" +
	"\x13UploadReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x11test_results_json\x18\x03 \x01(\tR\x0ftestResultsJson\"J\n" +
	"\x14UploadReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x12ClaimReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"I\n" +
	"\x13ClaimReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x11ReadReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"U\n" +
	"\x12ReadReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereport_content\x18\x02 \x01(\tR\rreportContent\"C\n" +
	"\fLoginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x9e\x01\n" +
	"\x13RegisterUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\"\xc9\x01\n" +
	"\x16RegisterInsurerRequest\x12\x1d\n" +
	"\n" +
	"insurer_id\x18\x01 \x01(\tR\tinsurerId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12%\n" +
	"\x0econtact_person\x18\x04 \x01(\tR\rcontactPerson\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa5\x01\n" +
	"\x06Report\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1b\n" +
	"\tclinic_id\x18\x02 \x01(\tR\bclinicId\x12!\n" +
	"\fpatient_hash\x18\x03 \x01(\tR\vpatientHash\x12\x1f\n" +
	"\vresult_json\x18\x04 \x01(\tR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"A\n" +
	"\x15ListMyReportsResponse\x12(\n" +
	"\areports\x18\x01 \x03(\v2\x0e.health.ReportR\areports\"\x82\x01\n" +
	"\x14RequestAccessRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\x03R\x06expiry\"K\n" +
	"\x15RequestAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xca\x02\n" +
	"\rAccessRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12!\n" +
	"\fpatient_hash\x18\x03 \x01(\tR\vpatientHash\x12%\n" +
	"\x0erequester_hash\x18\x04 \x01(\tR\rrequesterHash\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x06 \x01(\x03R\vrequestedAt\x12\x16\n" +
	"\x06expiry\x18\a \x01(\x03R\x06expiry\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0erequester_name\x18\t \x01(\tR\rrequesterName\x12!\n" +
	"\fcompany_name\x18\n" +
	" \x01(\tR\vcompanyName\"O\n" +
	"\x1aListAccessRequestsResponse\x121\n" +
	"\brequests\x18\x01 \x03(\v2\x15.health.AccessRequestR\brequests\"<\n" +
	"\x1bApproveAccessRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"R\n" +
	"\x1cApproveAccessRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x1aRejectAccessRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"Q\n" +
	"\x1bRejectAccessRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x01\n" +
	"\x1dInsurerDashboardStatsResponse\x12)\n" +
	"\x10total_authorized\x18\x01 \x01(\x05R\x0ftotalAuthorized\x12)\n" +
	"\x10pending_requests\x18\x02 \x01(\x05R\x0fpendingRequests\x12%\n" +
	"\x0etotal_patients\x18\x03 \x01(\x05R\rtotalPatients\"z\n" +
	"\x10AuthorizedReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\tR\x06expiry\"S\n" +
	"\x1dListAuthorizedReportsResponse\x122\n" +
	"\areports\x18\x01 \x03(\v2\x18.health.AuthorizedReportR\areports\"1\n" +
	"\x10PatientIDRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"e\n" +
	"\n" +
	"ReportMeta\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1b\n" +
	"\tclinic_id\x18\x02 \x01(\tR\bclinicId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"F\n" +
	"\x16ListReportMetaResponse\x12,\n" +
	"\areports\x18\x01 \x03(\v2\x12.health.ReportMetaR\areports\"S\n" +
	"\x1bViewAuthorizedReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Y\n" +
	"\x1cViewAuthorizedReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson*>\n" +
	"\x13AccessRequestStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x022\x97\r\n" +
	"\rHealthService\x12`\n" +
	"\fUploadReport\x12\x1b.health.UploadReportRequest\x1a\x1c.health.UploadReportResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/upload\x12\\\n" +
	"\vClaimReport\x12\x1a.health.ClaimReportRequest\x1a\x1b.health.ClaimReportResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/claim\x12c\n" +
	"\n" +
	"ReadReport\x12\x19.health.ReadReportRequest\x1a\x1a.health.ReadReportResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/report/{report_id}\x12J\n" +
	"\x05Login\x12\x14.health.LoginRequest\x1a\x15.health.LoginResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12c\n" +
	"\fRegisterUser\x12\x1b.health.RegisterUserRequest\x1a\x18.health.RegisterResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/register/user\x12l\n" +
	"\x0fRegisterInsurer\x12\x1e.health.RegisterInsurerRequest\x1a\x18.health.RegisterResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/register/insurer\x12[\n" +
	"\rListMyReports\x12\x16.google.protobuf.Empty\x1a\x1d.health.ListMyReportsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/reports\x12k\n" +
	"\rRequestAccess\x12\x1c.health.RequestAccessRequest\x1a\x1d.health.RequestAccessResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/access/request\x12m\n" +
	"\x12ListAccessRequests\x12\x16.google.protobuf.Empty\x1a\".health.ListAccessRequestsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/access/requests\x12\x80\x01\n" +
	"\x14ApproveAccessRequest\x12#.health.ApproveAccessRequestRequest\x1a$.health.ApproveAccessRequestResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/access/approve\x12|\n" +
	"\x13RejectAccessRequest\x12\".health.RejectAccessRequestRequest\x1a#.health.RejectAccessRequestResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/access/reject\x12x\n" +
	"\x18GetInsurerDashboardStats\x12\x16.google.protobuf.Empty\x1a%.health.InsurerDashboardStatsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/dashboard/summary\x12v\n" +
	"\x15ListAuthorizedReports\x12\x16.google.protobuf.Empty\x1a%.health.ListAuthorizedReportsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/reports/authorized\x12|\n" +
	"\x19ListReportMetaByPatientID\x12\x18.health.PatientIDRequest\x1a\x1e.health.ListReportMetaResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/reports/meta/{patient_id}\x12\x97\x01\n" +
	"\x14ViewAuthorizedReport\x12#.health.ViewAuthorizedReportRequest\x1a$.health.ViewAuthorizedReportResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/reports/authorized/{user_id}/{report_id}B\x17Z\x15sdk_test/proto;healthb\x06proto3"

var (
	file_proto_data_proto_rawDescOnce sync.Once
	file_proto_data_proto_rawDescData []byte
)

func file_proto_data_proto_rawDescGZIP() []byte {
	file_proto_data_proto_rawDescOnce.Do(func() {
		file_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)))
	})
	return file_proto_data_proto_rawDescData
}

var file_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_data_proto_goTypes = []any{
	(AccessRequestStatus)(0),              // 0: health.AccessRequestStatus
	(*UploadReportRequest)(nil),           // 1: health.UploadReportRequest
	(*UploadReportResponse)(nil),          // 2: health.UploadReportResponse
	(*ClaimReportRequest)(nil),            // 3: health.ClaimReportRequest
	(*ClaimReportResponse)(nil),           // 4: health.ClaimReportResponse
	(*ReadReportRequest)(nil),             // 5: health.ReadReportRequest
	(*ReadReportResponse)(nil),            // 6: health.ReadReportResponse
	(*LoginRequest)(nil),                  // 7: health.LoginRequest
	(*LoginResponse)(nil),                 // 8: health.LoginResponse
	(*RegisterUserRequest)(nil),           // 9: health.RegisterUserRequest
	(*RegisterInsurerRequest)(nil),        // 10: health.RegisterInsurerRequest
	(*RegisterResponse)(nil),              // 11: health.RegisterResponse
	(*Report)(nil),                        // 12: health.Report
	(*ListMyReportsResponse)(nil),         // 13: health.ListMyReportsResponse
	(*RequestAccessRequest)(nil),          // 14: health.RequestAccessRequest
	(*RequestAccessResponse)(nil),         // 15: health.RequestAccessResponse
	(*AccessRequest)(nil),                 // 16: health.AccessRequest
	(*ListAccessRequestsResponse)(nil),    // 17: health.ListAccessRequestsResponse
	(*ApproveAccessRequestRequest)(nil),   // 18: health.ApproveAccessRequestRequest
	(*ApproveAccessRequestResponse)(nil),  // 19: health.ApproveAccessRequestResponse
	(*RejectAccessRequestRequest)(nil),    // 20: health.RejectAccessRequestRequest
	(*RejectAccessRequestResponse)(nil),   // 21: health.RejectAccessRequestResponse
	(*InsurerDashboardStatsResponse)(nil), // 22: health.InsurerDashboardStatsResponse
	(*AuthorizedReport)(nil),              // 23: health.AuthorizedReport
	(*ListAuthorizedReportsResponse)(nil), // 24: health.ListAuthorizedReportsResponse
	(*PatientIDRequest)(nil),              // 25: health.PatientIDRequest
	(*ReportMeta)(nil),                    // 26: health.ReportMeta
	(*ListReportMetaResponse)(nil),        // 27: health.ListReportMetaResponse
	(*ViewAuthorizedReportRequest)(nil),   // 28: health.ViewAuthorizedReportRequest
	(*ViewAuthorizedReportResponse)(nil),  // 29: health.ViewAuthorizedReportResponse
	(*emptypb.Empty)(nil),                 // 30: google.protobuf.Empty
}
var file_proto_data_proto_depIdxs = []int32{
	12, // 0: health.ListMyReportsResponse.reports:type_name -> health.Report
	16, // 1: health.ListAccessRequestsResponse.requests:type_name -> health.AccessRequest
	23, // 2: health.ListAuthorizedReportsResponse.reports:type_name -> health.AuthorizedReport
	26, // 3: health.ListReportMetaResponse.reports:type_name -> health.ReportMeta
	1,  // 4: health.HealthService.UploadReport:input_type -> health.UploadReportRequest
	3,  // 5: health.HealthService.ClaimReport:input_type -> health.ClaimReportRequest
	5,  // 6: health.HealthService.ReadReport:input_type -> health.ReadReportRequest
	7,  // 7: health.HealthService.Login:input_type -> health.LoginRequest
	9,  // 8: health.HealthService.RegisterUser:input_type -> health.RegisterUserRequest
	10, // 9: health.HealthService.RegisterInsurer:input_type -> health.RegisterInsurerRequest
	30, // 10: health.HealthService.ListMyReports:input_type -> google.protobuf.Empty
	14, // 11: health.HealthService.RequestAccess:input_type -> health.RequestAccessRequest
	30, // 12: health.HealthService.ListAccessRequests:input_type -> google.protobuf.Empty
	18, // 13: health.HealthService.ApproveAccessRequest:input_type -> health.ApproveAccessRequestRequest
	20, // 14: health.HealthService.RejectAccessRequest:input_type -> health.RejectAccessRequestRequest
	30, // 15: health.HealthService.GetInsurerDashboardStats:input_type -> google.protobuf.Empty
	30, // 16: health.HealthService.ListAuthorizedReports:input_type -> google.protobuf.Empty
	25, // 17: health.HealthService.ListReportMetaByPatientID:input_type -> health.PatientIDRequest
	28, // 18: health.HealthService.ViewAuthorizedReport:input_type -> health.ViewAuthorizedReportRequest
	2,  // 19: health.HealthService.UploadReport:output_type -> health.UploadReportResponse
	4,  // 20: health.HealthService.ClaimReport:output_type -> health.ClaimReportResponse
	6,  // 21: health.HealthService.ReadReport:output_type -> health.ReadReportResponse
	8,  // 22: health.HealthService.Login:output_type -> health.LoginResponse
	11, // 23: health.HealthService.RegisterUser:output_type -> health.RegisterResponse
	11, // 24: health.HealthService.RegisterInsurer:output_type -> health.RegisterResponse
	13, // 25: health.HealthService.ListMyReports:output_type -> health.ListMyReportsResponse
	15, // 26: health.HealthService.RequestAccess:output_type -> health.RequestAccessResponse
	17, // 27: health.HealthService.ListAccessRequests:output_type -> health.ListAccessRequestsResponse
	19, // 28: health.HealthService.ApproveAccessRequest:output_type -> health.ApproveAccessRequestResponse
	21, // 29: health.HealthService.RejectAccessRequest:output_type -> health.RejectAccessRequestResponse
	22, // 30: health.HealthService.GetInsurerDashboardStats:output_type -> health.InsurerDashboardStatsResponse
	24, // 31: health.HealthService.ListAuthorizedReports:output_type -> health.ListAuthorizedReportsResponse
	27, // 32: health.HealthService.ListReportMetaByPatientID:output_type -> health.ListReportMetaResponse
	29, // 33: health.HealthService.ViewAuthorizedReport:output_type -> health.ViewAuthorizedReportResponse
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_data_proto_init() }
func file_proto_data_proto_init() {
	if File_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_proto_goTypes,
		DependencyIndexes: file_proto_data_proto_depIdxs,
		EnumInfos:         file_proto_data_proto_enumTypes,
		MessageInfos:      file_proto_data_proto_msgTypes,
	}.Build()
	File_proto_data_proto = out.File
	file_proto_data_proto_goTypes = nil
	file_proto_data_proto_depIdxs = nil
}
