from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def create_health_report_pdf(filename):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    # 標題
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, 750, "Medical Health Check Report")

    # 基本資料
    c.setFont("Helvetica", 12)
    c.drawString(50, 720, "Name: Test User")
    c.drawString(50, 705, "Date: 2025-11-23")
    c.drawString(50, 690, "ID: A123456789")

    # 畫一條線
    c.line(50, 680, 550, 680)

    # 測試數據 (使用極端異常值來測試 AI 反應)
    data = [
        ("Glu-AC (Glucose Ante Cibum)", "200 mg/dL"),
        ("HbA1c (Glycated Hemoglobin)", "8.5 %"),
        ("LDL-C (Low-Density Lipoprotein)", "900 mg/dL"),
        ("HDL-C (High-Density Lipoprotein)", "80 mg/dL"),
        ("TG (Triglycerides)", "150 mg/dL"),
        ("ALT (GPT)", "140 U/L"),
        ("CRE (Creatinine)", "6.0 mg/dL"),
        ("Hb (Hemoglobin)", "7.5 g/dL"),
        ("WBC (White Blood Cell)", "16.0 10^3/uL")
    ]

    y = 650
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Test Item")
    c.drawString(350, y, "Result")
    y -= 20

    c.setFont("Helvetica", 12)
    for item, value in data:
        c.drawString(50, y, item)
        c.drawString(350, y, value)
        y -= 25

    # 頁尾
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Medledger-AI Test Script")

    c.save()
    print(f"✅ PDF 報告已建立: {filename}")

if __name__ == "__main__":
    create_health_report_pdf("my_test_report.pdf")