
services:     # 定義服務的層級
  root-ca:
    container_name: root-ca
    image: hyperledger/fabric-ca:1.5
    command: sh -c 'fabric-ca-server start -b admin:adminpw --port 7054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CSR_CN=root-ca
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./root-ca:/tmp/hyperledger/fabric-ca
    ports:
      - 7054:7054
    networks:
      fabric-net:
        ipv4_address: "172.20.0.9"
  ca-tls:     # 服務名稱
    container_name: ca-tls
    image: hyperledger/fabric-ca:1.5
    command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-tls
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./tls/ca:/tmp/hyperledger/fabric-ca
    networks:
      fabric-net:
        ipv4_address: "172.20.0.8"
    ports:
      - 7052:7052


  peer1-org1:
    container_name: peer1-org1
    image: hyperledger/fabric-peer
    hostname: peer1.org1.example.com
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_CHAINCODE_LISTENADDRESS=0.0.0.0:7055
      - CORE_CHAINCODE_ADDRESS=peer1.org1.example.com:7055  
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org1/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-net
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org1/peer1/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org1/peer1/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org1/peer1/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
      - CORE_OPERATIONS_TLS_ENABLED=true
      - CORE_OPERATIONS_TLS_CERT_FILE=/tmp/hyperledger/org1/peer1/tls/server.crt
      - CORE_OPERATIONS_TLS_KEY_FILE=/tmp/hyperledger/org1/peer1/tls/server.key
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer1
    volumes:
      - /var/run:/host/var/run
      - /home/WOW/hyperledger/orgs/org1.example.com/peers/peer1.org1.example.com:/tmp/hyperledger/org1/peer1
      - /home/WOW/hyperledger/orgs/org1.example.com/users/org1-admin:/tmp/hyperledger/org1/admin-client
      - /home/WOW/hyperledger/chaincode-go:/tmp/hyperledger/org1/chaincode
    ports:
      - 7051:7051
      - 9444:9444 
      - 7055:7055

    networks:
      fabric-net:
        ipv4_address: "172.20.0.2"


  peer2-org1:
    container_name: peer2-org1
    image: hyperledger/fabric-peer
    hostname: peer2.org1.example.com
    environment:
      - CORE_PEER_ID=peer2.org1.example.com
      - CORE_PEER_ADDRESS=peer2.org1.example.com:7053
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7053
      - CORE_CHAINCODE_LISTENADDRESS=0.0.0.0:7056
      - CORE_CHAINCODE_ADDRESS=peer2.org1.example.com:7056
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org1/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-net
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org1/peer2/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org1/peer2/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org1/peer2/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.example.com:7053
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9445
      - CORE_OPERATIONS_TLS_ENABLED=true
      - CORE_OPERATIONS_TLS_CERT_FILE=/tmp/hyperledger/org1/peer2/tls/server.crt
      - CORE_OPERATIONS_TLS_KEY_FILE=/tmp/hyperledger/org1/peer2/tls/server.key

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer2
    volumes:
      - /var/run:/host/var/run
      - /home/WOW/hyperledger/orgs/org1.example.com/peers/peer2.org1.example.com:/tmp/hyperledger/org1/peer2
      - /home/WOW/hyperledger/orgs/org1.example.com/users/org1-admin:/tmp/hyperledger/org1/admin-client
      - /home/WOW/hyperledger/chaincode-go:/tmp/hyperledger/org1/chaincode
    ports:
      - 7053:7053
      - 9445:9445
      - 7056:7056
    networks:
      fabric-net:
        ipv4_address: "172.20.0.3"

  orderer1-org1:
    container_name: orderer1-org1
    image: hyperledger/fabric-orderer
    hostname: orderer1.org1.example.com
    environment:
      - ORDERER_HOME=/tmp/hyperledger/orderer
      - ORDERER_HOST=orderer1.org1.example.com
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LOCALMSPID=Org1MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/org1/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/org1/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/org1/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_ROOTCAS=/tmp/hyperledger/org1/orderer/tls/ca.crt
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/org1/admin-client/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/org1/admin-client/tls/server.key
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/tmp/hyperledger/org1/admin-client/tls/ca.crt
      - ORDERER_ADMIN_TLS_ROOTCAS=/tmp/hyperledger/org1/admin-client/tls/ca.crt
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=/tmp/hyperledger/org1/orderer/tls/ca.crt
      
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_GENERAL_LOGLEVEL=debug
      
    volumes:
      - /home/WOW/hyperledger/orgs/org1.example.com/orderer/orderer1.org1.example.com:/tmp/hyperledger/org1/orderer/
      - /home/WOW/hyperledger/orgs/org1.example.com/users/org1-admin:/tmp/hyperledger/org1/admin-client
      - /home/WOW/hyperledger/chaincode-go:/tmp/hyperledger/org1/chaincode
    ports:
      - "7050:7050"
      - "9443:9443" 
    networks:
      fabric-net:
        ipv4_address: "172.20.0.4"


networks:     # 定義網路
  fabric-net:
    external: true    