// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: proto/data.proto

package health

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessRequestStatus int32

const (
	AccessRequestStatus_PENDING  AccessRequestStatus = 0
	AccessRequestStatus_APPROVED AccessRequestStatus = 1
	AccessRequestStatus_REJECTED AccessRequestStatus = 2
)

// Enum value maps for AccessRequestStatus.
var (
	AccessRequestStatus_name = map[int32]string{
		0: "PENDING",
		1: "APPROVED",
		2: "REJECTED",
	}
	AccessRequestStatus_value = map[string]int32{
		"PENDING":  0,
		"APPROVED": 1,
		"REJECTED": 2,
	}
)

func (x AccessRequestStatus) Enum() *AccessRequestStatus {
	p := new(AccessRequestStatus)
	*p = x
	return p
}

func (x AccessRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_proto_enumTypes[0].Descriptor()
}

func (AccessRequestStatus) Type() protoreflect.EnumType {
	return &file_proto_data_proto_enumTypes[0]
}

func (x AccessRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRequestStatus.Descriptor instead.
func (AccessRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

// ========================
// 健康分析相關 Message（Python Backend 使用）
// ========================
type AnalyzeHealthReportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReportId        string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	PatientId       string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	TestResultsJson string                 `protobuf:"bytes,3,opt,name=test_results_json,json=testResultsJson,proto3" json:"test_results_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeHealthReportRequest) Reset() {
	*x = AnalyzeHealthReportRequest{}
	mi := &file_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeHealthReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeHealthReportRequest) ProtoMessage() {}

func (x *AnalyzeHealthReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeHealthReportRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeHealthReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeHealthReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AnalyzeHealthReportRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AnalyzeHealthReportRequest) GetTestResultsJson() string {
	if x != nil {
		return x.TestResultsJson
	}
	return ""
}

// 用戶端專用：摘要、分數、個人風險、推薦、健康計畫
type DiseaseRisk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disease       string                 `protobuf:"bytes,1,opt,name=disease,proto3" json:"disease,omitempty"`                             // 疾病名稱
	RiskPercent   int32                  `protobuf:"varint,2,opt,name=risk_percent,json=riskPercent,proto3" json:"risk_percent,omitempty"` // 風險百分比
	RiskLevel     string                 `protobuf:"bytes,3,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`        // "低風險"等
	MainFactors   []string               `protobuf:"bytes,4,rep,name=main_factors,json=mainFactors,proto3" json:"main_factors,omitempty"`  // 主因
	Advice        string                 `protobuf:"bytes,5,opt,name=advice,proto3" json:"advice,omitempty"`                               // 預防建議
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiseaseRisk) Reset() {
	*x = DiseaseRisk{}
	mi := &file_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiseaseRisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseaseRisk) ProtoMessage() {}

func (x *DiseaseRisk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseaseRisk.ProtoReflect.Descriptor instead.
func (*DiseaseRisk) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *DiseaseRisk) GetDisease() string {
	if x != nil {
		return x.Disease
	}
	return ""
}

func (x *DiseaseRisk) GetRiskPercent() int32 {
	if x != nil {
		return x.RiskPercent
	}
	return 0
}

func (x *DiseaseRisk) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *DiseaseRisk) GetMainFactors() []string {
	if x != nil {
		return x.MainFactors
	}
	return nil
}

func (x *DiseaseRisk) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

type UserHealthAnalysisResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	HealthScore             int32                  `protobuf:"varint,1,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"`                                    // 健康分數
	Summary                 string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`                                                                // 摘要
	PersonalAnalysis        string                 `protobuf:"bytes,3,opt,name=personal_analysis,json=personalAnalysis,proto3" json:"personal_analysis,omitempty"`                      // 個人健康分析
	DiseaseRisks            []*DiseaseRisk         `protobuf:"bytes,4,rep,name=disease_risks,json=diseaseRisks,proto3" json:"disease_risks,omitempty"`                                  // 疾病風險
	InsuranceRecommendation []string               `protobuf:"bytes,5,rep,name=insurance_recommendation,json=insuranceRecommendation,proto3" json:"insurance_recommendation,omitempty"` // 智能保險推薦
	ProtectionPlan          []string               `protobuf:"bytes,6,rep,name=protection_plan,json=protectionPlan,proto3" json:"protection_plan,omitempty"`                            // 健康防護計畫
	Success                 bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserHealthAnalysisResponse) Reset() {
	*x = UserHealthAnalysisResponse{}
	mi := &file_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHealthAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHealthAnalysisResponse) ProtoMessage() {}

func (x *UserHealthAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHealthAnalysisResponse.ProtoReflect.Descriptor instead.
func (*UserHealthAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *UserHealthAnalysisResponse) GetHealthScore() int32 {
	if x != nil {
		return x.HealthScore
	}
	return 0
}

func (x *UserHealthAnalysisResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UserHealthAnalysisResponse) GetPersonalAnalysis() string {
	if x != nil {
		return x.PersonalAnalysis
	}
	return ""
}

func (x *UserHealthAnalysisResponse) GetDiseaseRisks() []*DiseaseRisk {
	if x != nil {
		return x.DiseaseRisks
	}
	return nil
}

func (x *UserHealthAnalysisResponse) GetInsuranceRecommendation() []string {
	if x != nil {
		return x.InsuranceRecommendation
	}
	return nil
}

func (x *UserHealthAnalysisResponse) GetProtectionPlan() []string {
	if x != nil {
		return x.ProtectionPlan
	}
	return nil
}

func (x *UserHealthAnalysisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 保險業者專用：核保分數、分類風險、核保建議
type DiseaseRiskForInsurer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disease       string                 `protobuf:"bytes,1,opt,name=disease,proto3" json:"disease,omitempty"`
	RiskScore     int32                  `protobuf:"varint,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"` // 分數（如45分）
	RiskLevel     string                 `protobuf:"bytes,3,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`  // "低風險"
	MainFactors   []string               `protobuf:"bytes,4,rep,name=main_factors,json=mainFactors,proto3" json:"main_factors,omitempty"`
	Advice        string                 `protobuf:"bytes,5,opt,name=advice,proto3" json:"advice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiseaseRiskForInsurer) Reset() {
	*x = DiseaseRiskForInsurer{}
	mi := &file_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiseaseRiskForInsurer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseaseRiskForInsurer) ProtoMessage() {}

func (x *DiseaseRiskForInsurer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseaseRiskForInsurer.ProtoReflect.Descriptor instead.
func (*DiseaseRiskForInsurer) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *DiseaseRiskForInsurer) GetDisease() string {
	if x != nil {
		return x.Disease
	}
	return ""
}

func (x *DiseaseRiskForInsurer) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *DiseaseRiskForInsurer) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *DiseaseRiskForInsurer) GetMainFactors() []string {
	if x != nil {
		return x.MainFactors
	}
	return nil
}

func (x *DiseaseRiskForInsurer) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

type InsurerHealthAnalysisResponse struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	OverallRiskScore      int32                    `protobuf:"varint,1,opt,name=overall_risk_score,json=overallRiskScore,proto3" json:"overall_risk_score,omitempty"`               // 整體風險分數
	RiskLevelLabel        string                   `protobuf:"bytes,2,opt,name=risk_level_label,json=riskLevelLabel,proto3" json:"risk_level_label,omitempty"`                      // 低/中/高風險客戶
	Summary               string                   `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                                                            // 專業核保摘要
	CoreRecommendation    []string                 `protobuf:"bytes,4,rep,name=core_recommendation,json=coreRecommendation,proto3" json:"core_recommendation,omitempty"`            // 專業核保建議
	DiseaseRiskEvaluation []*DiseaseRiskForInsurer `protobuf:"bytes,5,rep,name=disease_risk_evaluation,json=diseaseRiskEvaluation,proto3" json:"disease_risk_evaluation,omitempty"` // 疾病分類風險
	Success               bool                     `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InsurerHealthAnalysisResponse) Reset() {
	*x = InsurerHealthAnalysisResponse{}
	mi := &file_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsurerHealthAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsurerHealthAnalysisResponse) ProtoMessage() {}

func (x *InsurerHealthAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsurerHealthAnalysisResponse.ProtoReflect.Descriptor instead.
func (*InsurerHealthAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *InsurerHealthAnalysisResponse) GetOverallRiskScore() int32 {
	if x != nil {
		return x.OverallRiskScore
	}
	return 0
}

func (x *InsurerHealthAnalysisResponse) GetRiskLevelLabel() string {
	if x != nil {
		return x.RiskLevelLabel
	}
	return ""
}

func (x *InsurerHealthAnalysisResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *InsurerHealthAnalysisResponse) GetCoreRecommendation() []string {
	if x != nil {
		return x.CoreRecommendation
	}
	return nil
}

func (x *InsurerHealthAnalysisResponse) GetDiseaseRiskEvaluation() []*DiseaseRiskForInsurer {
	if x != nil {
		return x.DiseaseRiskEvaluation
	}
	return nil
}

func (x *InsurerHealthAnalysisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ========================
// Hyperledger Fabric 相關 Message（Go Server 使用）
// ========================
type UploadReportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReportId        string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TestResultsJson string                 `protobuf:"bytes,3,opt,name=test_results_json,json=testResultsJson,proto3" json:"test_results_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadReportRequest) Reset() {
	*x = UploadReportRequest{}
	mi := &file_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReportRequest) ProtoMessage() {}

func (x *UploadReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReportRequest.ProtoReflect.Descriptor instead.
func (*UploadReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *UploadReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *UploadReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadReportRequest) GetTestResultsJson() string {
	if x != nil {
		return x.TestResultsJson
	}
	return ""
}

type UploadReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReportResponse) Reset() {
	*x = UploadReportResponse{}
	mi := &file_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReportResponse) ProtoMessage() {}

func (x *UploadReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReportResponse.ProtoReflect.Descriptor instead.
func (*UploadReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{6}
}

func (x *UploadReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadMyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMyReportRequest) Reset() {
	*x = ReadMyReportRequest{}
	mi := &file_proto_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMyReportRequest) ProtoMessage() {}

func (x *ReadMyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMyReportRequest.ProtoReflect.Descriptor instead.
func (*ReadMyReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{7}
}

func (x *ReadMyReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ReadMyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMyReportResponse) Reset() {
	*x = ReadMyReportResponse{}
	mi := &file_proto_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMyReportResponse) ProtoMessage() {}

func (x *ReadMyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMyReportResponse.ProtoReflect.Descriptor instead.
func (*ReadMyReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{8}
}

func (x *ReadMyReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadMyReportResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type ListMyReportMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ReportMeta          `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyReportMetaResponse) Reset() {
	*x = ListMyReportMetaResponse{}
	mi := &file_proto_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyReportMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyReportMetaResponse) ProtoMessage() {}

func (x *ListMyReportMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyReportMetaResponse.ProtoReflect.Descriptor instead.
func (*ListMyReportMetaResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{9}
}

func (x *ListMyReportMetaResponse) GetReports() []*ReportMeta {
	if x != nil {
		return x.Reports
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{10}
}

func (x *LoginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{11}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_proto_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterInsurerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsurerId     string                 `protobuf:"bytes,1,opt,name=insurer_id,json=insurerId,proto3" json:"insurer_id,omitempty"` // 例如: CATHAY-01
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CompanyName   string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	ContactPerson string                 `protobuf:"bytes,4,opt,name=contact_person,json=contactPerson,proto3" json:"contact_person,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInsurerRequest) Reset() {
	*x = RegisterInsurerRequest{}
	mi := &file_proto_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInsurerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInsurerRequest) ProtoMessage() {}

func (x *RegisterInsurerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInsurerRequest.ProtoReflect.Descriptor instead.
func (*RegisterInsurerRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterInsurerRequest) GetInsurerId() string {
	if x != nil {
		return x.InsurerId
	}
	return ""
}

func (x *RegisterInsurerRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterInsurerRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *RegisterInsurerRequest) GetContactPerson() string {
	if x != nil {
		return x.ContactPerson
	}
	return ""
}

func (x *RegisterInsurerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterInsurerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ClinicId      string                 `protobuf:"bytes,2,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	PatientHash   string                 `protobuf:"bytes,3,opt,name=patient_hash,json=patientHash,proto3" json:"patient_hash,omitempty"`
	ResultJson    string                 `protobuf:"bytes,4,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_proto_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{15}
}

func (x *Report) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *Report) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *Report) GetPatientHash() string {
	if x != nil {
		return x.PatientHash
	}
	return ""
}

func (x *Report) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *Report) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListMyReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyReportsResponse) Reset() {
	*x = ListMyReportsResponse{}
	mi := &file_proto_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyReportsResponse) ProtoMessage() {}

func (x *ListMyReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyReportsResponse.ProtoReflect.Descriptor instead.
func (*ListMyReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{16}
}

func (x *ListMyReportsResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

// 🔵 保險業者送出授權申請
type RequestAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Expiry        int64                  `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"` // Unix 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccessRequest) Reset() {
	*x = RequestAccessRequest{}
	mi := &file_proto_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccessRequest) ProtoMessage() {}

func (x *RequestAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccessRequest.ProtoReflect.Descriptor instead.
func (*RequestAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{17}
}

func (x *RequestAccessRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *RequestAccessRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RequestAccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RequestAccessRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type RequestAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccessResponse) Reset() {
	*x = RequestAccessResponse{}
	mi := &file_proto_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccessResponse) ProtoMessage() {}

func (x *RequestAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccessResponse.ProtoReflect.Descriptor instead.
func (*RequestAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{18}
}

func (x *RequestAccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestAccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestAccessResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 🟢 病患查詢自己的待審申請
type AccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	PatientHash   string                 `protobuf:"bytes,3,opt,name=patient_hash,json=patientHash,proto3" json:"patient_hash,omitempty"`
	RequesterHash string                 `protobuf:"bytes,4,opt,name=requester_hash,json=requesterHash,proto3" json:"requester_hash,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedAt   int64                  `protobuf:"varint,6,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	Expiry        int64                  `protobuf:"varint,7,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	RequesterName string                 `protobuf:"bytes,9,opt,name=requester_name,json=requesterName,proto3" json:"requester_name,omitempty"`
	CompanyName   string                 `protobuf:"bytes,10,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	PatientName   string                 `protobuf:"bytes,11,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"` // 病患真實姓名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_proto_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{19}
}

func (x *AccessRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AccessRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AccessRequest) GetPatientHash() string {
	if x != nil {
		return x.PatientHash
	}
	return ""
}

func (x *AccessRequest) GetRequesterHash() string {
	if x != nil {
		return x.RequesterHash
	}
	return ""
}

func (x *AccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AccessRequest) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *AccessRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *AccessRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccessRequest) GetRequesterName() string {
	if x != nil {
		return x.RequesterName
	}
	return ""
}

func (x *AccessRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *AccessRequest) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

type ListAccessRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*AccessRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessRequestsResponse) Reset() {
	*x = ListAccessRequestsResponse{}
	mi := &file_proto_data_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessRequestsResponse) ProtoMessage() {}

func (x *ListAccessRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListAccessRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{20}
}

func (x *ListAccessRequestsResponse) GetRequests() []*AccessRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// 🟡 病患點同意授權
type ApproveAccessRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAccessRequestRequest) Reset() {
	*x = ApproveAccessRequestRequest{}
	mi := &file_proto_data_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAccessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAccessRequestRequest) ProtoMessage() {}

func (x *ApproveAccessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAccessRequestRequest.ProtoReflect.Descriptor instead.
func (*ApproveAccessRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{21}
}

func (x *ApproveAccessRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApproveAccessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAccessRequestResponse) Reset() {
	*x = ApproveAccessRequestResponse{}
	mi := &file_proto_data_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAccessRequestResponse) ProtoMessage() {}

func (x *ApproveAccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAccessRequestResponse.ProtoReflect.Descriptor instead.
func (*ApproveAccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{22}
}

func (x *ApproveAccessRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApproveAccessRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 🔴 病患拒絕授權
type RejectAccessRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectAccessRequestRequest) Reset() {
	*x = RejectAccessRequestRequest{}
	mi := &file_proto_data_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectAccessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectAccessRequestRequest) ProtoMessage() {}

func (x *RejectAccessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectAccessRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectAccessRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{23}
}

func (x *RejectAccessRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RejectAccessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectAccessRequestResponse) Reset() {
	*x = RejectAccessRequestResponse{}
	mi := &file_proto_data_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectAccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectAccessRequestResponse) ProtoMessage() {}

func (x *RejectAccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectAccessRequestResponse.ProtoReflect.Descriptor instead.
func (*RejectAccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{24}
}

func (x *RejectAccessRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RejectAccessRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InsurerDashboardStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalAuthorized int32                  `protobuf:"varint,1,opt,name=total_authorized,json=totalAuthorized,proto3" json:"total_authorized,omitempty"`
	PendingRequests int32                  `protobuf:"varint,2,opt,name=pending_requests,json=pendingRequests,proto3" json:"pending_requests,omitempty"`
	TotalPatients   int32                  `protobuf:"varint,3,opt,name=total_patients,json=totalPatients,proto3" json:"total_patients,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsurerDashboardStatsResponse) Reset() {
	*x = InsurerDashboardStatsResponse{}
	mi := &file_proto_data_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsurerDashboardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsurerDashboardStatsResponse) ProtoMessage() {}

func (x *InsurerDashboardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsurerDashboardStatsResponse.ProtoReflect.Descriptor instead.
func (*InsurerDashboardStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{25}
}

func (x *InsurerDashboardStatsResponse) GetTotalAuthorized() int32 {
	if x != nil {
		return x.TotalAuthorized
	}
	return 0
}

func (x *InsurerDashboardStatsResponse) GetPendingRequests() int32 {
	if x != nil {
		return x.PendingRequests
	}
	return 0
}

func (x *InsurerDashboardStatsResponse) GetTotalPatients() int32 {
	if x != nil {
		return x.TotalPatients
	}
	return 0
}

type AuthorizedReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Expiry        string                 `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	PatientName   string                 `protobuf:"bytes,6,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"` // 病患真實姓名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedReport) Reset() {
	*x = AuthorizedReport{}
	mi := &file_proto_data_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedReport) ProtoMessage() {}

func (x *AuthorizedReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedReport.ProtoReflect.Descriptor instead.
func (*AuthorizedReport) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{26}
}

func (x *AuthorizedReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AuthorizedReport) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AuthorizedReport) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AuthorizedReport) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *AuthorizedReport) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

type ListAuthorizedReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*AuthorizedReport    `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorizedReportsResponse) Reset() {
	*x = ListAuthorizedReportsResponse{}
	mi := &file_proto_data_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorizedReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorizedReportsResponse) ProtoMessage() {}

func (x *ListAuthorizedReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorizedReportsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorizedReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{27}
}

func (x *ListAuthorizedReportsResponse) GetReports() []*AuthorizedReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type PatientIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientIDRequest) Reset() {
	*x = PatientIDRequest{}
	mi := &file_proto_data_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientIDRequest) ProtoMessage() {}

func (x *PatientIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientIDRequest.ProtoReflect.Descriptor instead.
func (*PatientIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{28}
}

func (x *PatientIDRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type ReportMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ClinicId      string                 `protobuf:"bytes,2,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMeta) Reset() {
	*x = ReportMeta{}
	mi := &file_proto_data_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMeta) ProtoMessage() {}

func (x *ReportMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMeta.ProtoReflect.Descriptor instead.
func (*ReportMeta) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{29}
}

func (x *ReportMeta) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportMeta) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *ReportMeta) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListReportMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ReportMeta          `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportMetaResponse) Reset() {
	*x = ListReportMetaResponse{}
	mi := &file_proto_data_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportMetaResponse) ProtoMessage() {}

func (x *ListReportMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportMetaResponse.ProtoReflect.Descriptor instead.
func (*ListReportMetaResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{30}
}

func (x *ListReportMetaResponse) GetReports() []*ReportMeta {
	if x != nil {
		return x.Reports
	}
	return nil
}

type ViewAuthorizedReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAuthorizedReportRequest) Reset() {
	*x = ViewAuthorizedReportRequest{}
	mi := &file_proto_data_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAuthorizedReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAuthorizedReportRequest) ProtoMessage() {}

func (x *ViewAuthorizedReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAuthorizedReportRequest.ProtoReflect.Descriptor instead.
func (*ViewAuthorizedReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{31}
}

func (x *ViewAuthorizedReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ViewAuthorizedReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ViewAuthorizedReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // 報告全文或格式化內容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAuthorizedReportResponse) Reset() {
	*x = ViewAuthorizedReportResponse{}
	mi := &file_proto_data_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAuthorizedReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAuthorizedReportResponse) ProtoMessage() {}

func (x *ViewAuthorizedReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAuthorizedReportResponse.ProtoReflect.Descriptor instead.
func (*ViewAuthorizedReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{32}
}

func (x *ViewAuthorizedReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ViewAuthorizedReportResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type ListMyAccessRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Requests      []*AccessRequest       `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyAccessRequestsResponse) Reset() {
	*x = ListMyAccessRequestsResponse{}
	mi := &file_proto_data_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyAccessRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyAccessRequestsResponse) ProtoMessage() {}

func (x *ListMyAccessRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyAccessRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListMyAccessRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{33}
}

func (x *ListMyAccessRequestsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListMyAccessRequestsResponse) GetRequests() []*AccessRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type AuthTicket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientHash   string                 `protobuf:"bytes,1,opt,name=patient_hash,json=patientHash,proto3" json:"patient_hash,omitempty"`
	TargetHash    string                 `protobuf:"bytes,2,opt,name=target_hash,json=targetHash,proto3" json:"target_hash,omitempty"`
	ReportId      string                 `protobuf:"bytes,3,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	GrantedAt     int64                  `protobuf:"varint,4,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	Expiry        int64                  `protobuf:"varint,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	RequesterName string                 `protobuf:"bytes,6,opt,name=requester_name,json=requesterName,proto3" json:"requester_name,omitempty"` // 保險業者名稱
	CompanyName   string                 `protobuf:"bytes,7,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`       // 公司名稱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTicket) Reset() {
	*x = AuthTicket{}
	mi := &file_proto_data_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTicket) ProtoMessage() {}

func (x *AuthTicket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTicket.ProtoReflect.Descriptor instead.
func (*AuthTicket) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{34}
}

func (x *AuthTicket) GetPatientHash() string {
	if x != nil {
		return x.PatientHash
	}
	return ""
}

func (x *AuthTicket) GetTargetHash() string {
	if x != nil {
		return x.TargetHash
	}
	return ""
}

func (x *AuthTicket) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AuthTicket) GetGrantedAt() int64 {
	if x != nil {
		return x.GrantedAt
	}
	return 0
}

func (x *AuthTicket) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *AuthTicket) GetRequesterName() string {
	if x != nil {
		return x.RequesterName
	}
	return ""
}

func (x *AuthTicket) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type ListAuthorizedTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*AuthTicket          `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorizedTicketsResponse) Reset() {
	*x = ListAuthorizedTicketsResponse{}
	mi := &file_proto_data_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorizedTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorizedTicketsResponse) ProtoMessage() {}

func (x *ListAuthorizedTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorizedTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorizedTicketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{35}
}

func (x *ListAuthorizedTicketsResponse) GetTickets() []*AuthTicket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *ListAuthorizedTicketsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ========================
// 前端健檢分析相關 Message
// ========================
// 前端請求分析（通過報告 ID）
type AnalyzeReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`             // 報告 ID（從鏈上獲取）
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // 用戶 ID（可選，用於權限驗證）
	AnalysisType  string                 `protobuf:"bytes,3,opt,name=analysis_type,json=analysisType,proto3" json:"analysis_type,omitempty"` // 分析類型：user 或 insurer（默認 user）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeReportRequest) Reset() {
	*x = AnalyzeReportRequest{}
	mi := &file_proto_data_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeReportRequest) ProtoMessage() {}

func (x *AnalyzeReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeReportRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{36}
}

func (x *AnalyzeReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AnalyzeReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyzeReportRequest) GetAnalysisType() string {
	if x != nil {
		return x.AnalysisType
	}
	return ""
}

// 統一的健康分析回應（包含用戶和保險業者分析）
type HealthAnalysisResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 用戶分析結果（analysis_type = "user" 時返回）
	UserAnalysis *UserHealthAnalysisResponse `protobuf:"bytes,3,opt,name=user_analysis,json=userAnalysis,proto3" json:"user_analysis,omitempty"`
	// 保險業者分析結果（analysis_type = "insurer" 時返回）
	InsurerAnalysis *InsurerHealthAnalysisResponse `protobuf:"bytes,4,opt,name=insurer_analysis,json=insurerAnalysis,proto3" json:"insurer_analysis,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthAnalysisResponse) Reset() {
	*x = HealthAnalysisResponse{}
	mi := &file_proto_data_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAnalysisResponse) ProtoMessage() {}

func (x *HealthAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAnalysisResponse.ProtoReflect.Descriptor instead.
func (*HealthAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{37}
}

func (x *HealthAnalysisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthAnalysisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthAnalysisResponse) GetUserAnalysis() *UserHealthAnalysisResponse {
	if x != nil {
		return x.UserAnalysis
	}
	return nil
}

func (x *HealthAnalysisResponse) GetInsurerAnalysis() *InsurerHealthAnalysisResponse {
	if x != nil {
		return x.InsurerAnalysis
	}
	return nil
}

var File_proto_data_proto protoreflect.FileDescriptor

const file_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x10proto/data.proto\x12\x06health\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x01\n" +
	"\x1aAnalyzeHealthReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12*\n" +
	"\x11test_results_json\x18\x03 \x01(\tR\x0ftestResultsJson\"\xa4\x01\n" +
	"\vDiseaseRisk\x12\x18\n" +
	"\adisease\x18\x01 \x01(\tR\adisease\x12!\n" +
	"\frisk_percent\x18\x02 \x01(\x05R\vriskPercent\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x03 \x01(\tR\triskLevel\x12!\n" +
	"\fmain_factors\x18\x04 \x03(\tR\vmainFactors\x12\x16\n" +
	"\x06advice\x18\x05 \x01(\tR\x06advice\"\xbe\x02\n" +
	"\x1aUserHealthAnalysisResponse\x12!\n" +
	"\fhealth_score\x18\x01 \x01(\x05R\vhealthScore\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12+\n" +
	"\x11personal_analysis\x18\x03 \x01(\tR\x10personalAnalysis\x128\n" +
	"\rdisease_risks\x18\x04 \x03(\v2\x13.health.DiseaseRiskR\fdiseaseRisks\x129\n" +
	"\x18insurance_recommendation\x18\x05 \x03(\tR\x17insuranceRecommendation\x12'\n" +
	"\x0fprotection_plan\x18\x06 \x03(\tR\x0eprotectionPlan\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\"\xaa\x01\n" +
	"\x15DiseaseRiskForInsurer\x12\x18\n" +
	"\adisease\x18\x01 \x01(\tR\adisease\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x05R\triskScore\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x03 \x01(\tR\triskLevel\x12!\n" +
	"\fmain_factors\x18\x04 \x03(\tR\vmainFactors\x12\x16\n" +
	"\x06advice\x18\x05 \x01(\tR\x06advice\"\xb3\x02\n" +
	"\x1dInsurerHealthAnalysisResponse\x12,\n" +
	"\x12overall_risk_score\x18\x01 \x01(\x05R\x10overallRiskScore\x12(\n" +
	"\x10risk_level_label\x18\x02 \x01(\tR\x0eriskLevelLabel\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12/\n" +
	"\x13core_recommendation\x18\x04 \x03(\tR\x12coreRecommendation\x12U\n" +
	"\x17disease_risk_evaluation\x18\x05 \x03(\v2\x1d.health.DiseaseRiskForInsurerR\x15diseaseRiskEvaluation\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\"w\n" +
	"\x13UploadReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x11test_results_json\x18\x03 \x01(\tR\x0ftestResultsJson\"J\n" +
	"\x14UploadReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x13ReadMyReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"Q\n" +
	"\x14ReadMyReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\"H\n" +
	"\x18ListMyReportMetaResponse\x12,\n" +
	"\areports\x18\x01 \x03(\v2\x12.health.ReportMetaR\areports\"C\n" +
	"\fLoginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x9e\x01\n" +
	"\x13RegisterUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\"\xc9\x01\n" +
	"\x16RegisterInsurerRequest\x12\x1d\n" +
	"\n" +
	"insurer_id\x18\x01 \x01(\tR\tinsurerId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12%\n" +
	"\x0econtact_person\x18\x04 \x01(\tR\rcontactPerson\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa5\x01\n" +
	"\x06Report\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1b\n" +
	"\tclinic_id\x18\x02 \x01(\tR\bclinicId\x12!\n" +
	"\fpatient_hash\x18\x03 \x01(\tR\vpatientHash\x12\x1f\n" +
	"\vresult_json\x18\x04 \x01(\tR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"A\n" +
	"\x15ListMyReportsResponse\x12(\n" +
	"\areports\x18\x01 \x03(\v2\x0e.health.ReportR\areports\"\x82\x01\n" +
	"\x14RequestAccessRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\x03R\x06expiry\"j\n" +
	"\x15RequestAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\xed\x02\n" +
	"\rAccessRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12!\n" +
	"\fpatient_hash\x18\x03 \x01(\tR\vpatientHash\x12%\n" +
	"\x0erequester_hash\x18\x04 \x01(\tR\rrequesterHash\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12!\n" +
	"\frequested_at\x18\x06 \x01(\x03R\vrequestedAt\x12\x16\n" +
	"\x06expiry\x18\a \x01(\x03R\x06expiry\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0erequester_name\x18\t \x01(\tR\rrequesterName\x12!\n" +
	"\fcompany_name\x18\n" +
	" \x01(\tR\vcompanyName\x12!\n" +
	"\fpatient_name\x18\v \x01(\tR\vpatientName\"O\n" +
	"\x1aListAccessRequestsResponse\x121\n" +
	"\brequests\x18\x01 \x03(\v2\x15.health.AccessRequestR\brequests\"<\n" +
	"\x1bApproveAccessRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"R\n" +
	"\x1cApproveAccessRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x1aRejectAccessRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"Q\n" +
	"\x1bRejectAccessRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x01\n" +
	"\x1dInsurerDashboardStatsResponse\x12)\n" +
	"\x10total_authorized\x18\x01 \x01(\x05R\x0ftotalAuthorized\x12)\n" +
	"\x10pending_requests\x18\x02 \x01(\x05R\x0fpendingRequests\x12%\n" +
	"\x0etotal_patients\x18\x03 \x01(\x05R\rtotalPatients\"\x9d\x01\n" +
	"\x10AuthorizedReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\tR\x06expiry\x12!\n" +
	"\fpatient_name\x18\x06 \x01(\tR\vpatientName\"S\n" +
	"\x1dListAuthorizedReportsResponse\x122\n" +
	"\areports\x18\x01 \x03(\v2\x18.health.AuthorizedReportR\areports\"1\n" +
	"\x10PatientIDRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"e\n" +
	"\n" +
	"ReportMeta\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1b\n" +
	"\tclinic_id\x18\x02 \x01(\tR\bclinicId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"F\n" +
	"\x16ListReportMetaResponse\x12,\n" +
	"\areports\x18\x01 \x03(\v2\x12.health.ReportMetaR\areports\"S\n" +
	"\x1bViewAuthorizedReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Y\n" +
	"\x1cViewAuthorizedReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\"k\n" +
	"\x1cListMyAccessRequestsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\brequests\x18\x03 \x03(\v2\x15.health.AccessRequestR\brequests\"\xee\x01\n" +
	"\n" +
	"AuthTicket\x12!\n" +
	"\fpatient_hash\x18\x01 \x01(\tR\vpatientHash\x12\x1f\n" +
	"\vtarget_hash\x18\x02 \x01(\tR\n" +
	"targetHash\x12\x1b\n" +
	"\treport_id\x18\x03 \x01(\tR\breportId\x12\x1d\n" +
	"\n" +
	"granted_at\x18\x04 \x01(\x03R\tgrantedAt\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\x03R\x06expiry\x12%\n" +
	"\x0erequester_name\x18\x06 \x01(\tR\rrequesterName\x12!\n" +
	"\fcompany_name\x18\a \x01(\tR\vcompanyName\"g\n" +
	"\x1dListAuthorizedTicketsResponse\x12,\n" +
	"\atickets\x18\x01 \x03(\v2\x12.health.AuthTicketR\atickets\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"q\n" +
	"\x14AnalyzeReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\ranalysis_type\x18\x03 \x01(\tR\fanalysisType\"\xe7\x01\n" +
	"\x16HealthAnalysisResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\ruser_analysis\x18\x03 \x01(\v2\".health.UserHealthAnalysisResponseR\fuserAnalysis\x12P\n" +
	"\x10insurer_analysis\x18\x04 \x01(\v2%.health.InsurerHealthAnalysisResponseR\x0finsurerAnalysis*>\n" +
	"\x13AccessRequestStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x022\x88\x10\n" +
	"\rHealthService\x12f\n" +
	"\x1aAnalyzeHealthReportForUser\x12\".health.AnalyzeHealthReportRequest\x1a\".health.UserHealthAnalysisResponse\"\x00\x12l\n" +
	"\x1dAnalyzeHealthReportForInsurer\x12\".health.AnalyzeHealthReportRequest\x1a%.health.InsurerHealthAnalysisResponse\"\x00\x12p\n" +
	"\x11GetHealthAnalysis\x12\x1c.health.AnalyzeReportRequest\x1a\x1e.health.HealthAnalysisResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/health/analyze\x12`\n" +
	"\fUploadReport\x12\x1b.health.UploadReportRequest\x1a\x1c.health.UploadReportResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/upload\x12J\n" +
	"\x05Login\x12\x14.health.LoginRequest\x1a\x15.health.LoginResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12c\n" +
	"\fRegisterUser\x12\x1b.health.RegisterUserRequest\x1a\x18.health.RegisterResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/register/user\x12l\n" +
	"\x0fRegisterInsurer\x12\x1e.health.RegisterInsurerRequest\x1a\x18.health.RegisterResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/register/insurer\x12i\n" +
	"\x10ListMyReportMeta\x12\x16.google.protobuf.Empty\x1a .health.ListMyReportMetaResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/reports/my/meta\x12j\n" +
	"\fReadMyReport\x12\x1b.health.ReadMyReportRequest\x1a\x1c.health.ReadMyReportResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/reports/{report_id}\x12t\n" +
	"\x17ListMyAuthorizedTickets\x12\x16.google.protobuf.Empty\x1a%.health.ListAuthorizedTicketsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/access/tickets\x12k\n" +
	"\rRequestAccess\x12\x1c.health.RequestAccessRequest\x1a\x1d.health.RequestAccessResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/access/request\x12m\n" +
	"\x12ListAccessRequests\x12\x16.google.protobuf.Empty\x1a\".health.ListAccessRequestsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/access/requests\x12\x80\x01\n" +
	"\x14ApproveAccessRequest\x12#.health.ApproveAccessRequestRequest\x1a$.health.ApproveAccessRequestResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/access/approve\x12|\n" +
	"\x13RejectAccessRequest\x12\".health.RejectAccessRequestRequest\x1a#.health.RejectAccessRequestResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/access/reject\x12v\n" +
	"\x15ListAuthorizedReports\x12\x16.google.protobuf.Empty\x1a%.health.ListAuthorizedReportsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/reports/authorized\x12|\n" +
	"\x19ListReportMetaByPatientID\x12\x18.health.PatientIDRequest\x1a\x1e.health.ListReportMetaResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/reports/meta/{patient_id}\x12\x97\x01\n" +
	"\x14ViewAuthorizedReport\x12#.health.ViewAuthorizedReportRequest\x1a$.health.ViewAuthorizedReportResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/reports/authorized/{user_id}/{report_id}\x12t\n" +
	"\x14ListMyAccessRequests\x12\x16.google.protobuf.Empty\x1a$.health.ListMyAccessRequestsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/access/requests/myB\x18Z\x16go_server/proto;healthb\x06proto3"

var (
	file_proto_data_proto_rawDescOnce sync.Once
	file_proto_data_proto_rawDescData []byte
)

func file_proto_data_proto_rawDescGZIP() []byte {
	file_proto_data_proto_rawDescOnce.Do(func() {
		file_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)))
	})
	return file_proto_data_proto_rawDescData
}

var file_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_proto_data_proto_goTypes = []any{
	(AccessRequestStatus)(0),              // 0: health.AccessRequestStatus
	(*AnalyzeHealthReportRequest)(nil),    // 1: health.AnalyzeHealthReportRequest
	(*DiseaseRisk)(nil),                   // 2: health.DiseaseRisk
	(*UserHealthAnalysisResponse)(nil),    // 3: health.UserHealthAnalysisResponse
	(*DiseaseRiskForInsurer)(nil),         // 4: health.DiseaseRiskForInsurer
	(*InsurerHealthAnalysisResponse)(nil), // 5: health.InsurerHealthAnalysisResponse
	(*UploadReportRequest)(nil),           // 6: health.UploadReportRequest
	(*UploadReportResponse)(nil),          // 7: health.UploadReportResponse
	(*ReadMyReportRequest)(nil),           // 8: health.ReadMyReportRequest
	(*ReadMyReportResponse)(nil),          // 9: health.ReadMyReportResponse
	(*ListMyReportMetaResponse)(nil),      // 10: health.ListMyReportMetaResponse
	(*LoginRequest)(nil),                  // 11: health.LoginRequest
	(*LoginResponse)(nil),                 // 12: health.LoginResponse
	(*RegisterUserRequest)(nil),           // 13: health.RegisterUserRequest
	(*RegisterInsurerRequest)(nil),        // 14: health.RegisterInsurerRequest
	(*RegisterResponse)(nil),              // 15: health.RegisterResponse
	(*Report)(nil),                        // 16: health.Report
	(*ListMyReportsResponse)(nil),         // 17: health.ListMyReportsResponse
	(*RequestAccessRequest)(nil),          // 18: health.RequestAccessRequest
	(*RequestAccessResponse)(nil),         // 19: health.RequestAccessResponse
	(*AccessRequest)(nil),                 // 20: health.AccessRequest
	(*ListAccessRequestsResponse)(nil),    // 21: health.ListAccessRequestsResponse
	(*ApproveAccessRequestRequest)(nil),   // 22: health.ApproveAccessRequestRequest
	(*ApproveAccessRequestResponse)(nil),  // 23: health.ApproveAccessRequestResponse
	(*RejectAccessRequestRequest)(nil),    // 24: health.RejectAccessRequestRequest
	(*RejectAccessRequestResponse)(nil),   // 25: health.RejectAccessRequestResponse
	(*InsurerDashboardStatsResponse)(nil), // 26: health.InsurerDashboardStatsResponse
	(*AuthorizedReport)(nil),              // 27: health.AuthorizedReport
	(*ListAuthorizedReportsResponse)(nil), // 28: health.ListAuthorizedReportsResponse
	(*PatientIDRequest)(nil),              // 29: health.PatientIDRequest
	(*ReportMeta)(nil),                    // 30: health.ReportMeta
	(*ListReportMetaResponse)(nil),        // 31: health.ListReportMetaResponse
	(*ViewAuthorizedReportRequest)(nil),   // 32: health.ViewAuthorizedReportRequest
	(*ViewAuthorizedReportResponse)(nil),  // 33: health.ViewAuthorizedReportResponse
	(*ListMyAccessRequestsResponse)(nil),  // 34: health.ListMyAccessRequestsResponse
	(*AuthTicket)(nil),                    // 35: health.AuthTicket
	(*ListAuthorizedTicketsResponse)(nil), // 36: health.ListAuthorizedTicketsResponse
	(*AnalyzeReportRequest)(nil),          // 37: health.AnalyzeReportRequest
	(*HealthAnalysisResponse)(nil),        // 38: health.HealthAnalysisResponse
	(*emptypb.Empty)(nil),                 // 39: google.protobuf.Empty
}
var file_proto_data_proto_depIdxs = []int32{
	2,  // 0: health.UserHealthAnalysisResponse.disease_risks:type_name -> health.DiseaseRisk
	4,  // 1: health.InsurerHealthAnalysisResponse.disease_risk_evaluation:type_name -> health.DiseaseRiskForInsurer
	30, // 2: health.ListMyReportMetaResponse.reports:type_name -> health.ReportMeta
	16, // 3: health.ListMyReportsResponse.reports:type_name -> health.Report
	20, // 4: health.ListAccessRequestsResponse.requests:type_name -> health.AccessRequest
	27, // 5: health.ListAuthorizedReportsResponse.reports:type_name -> health.AuthorizedReport
	30, // 6: health.ListReportMetaResponse.reports:type_name -> health.ReportMeta
	20, // 7: health.ListMyAccessRequestsResponse.requests:type_name -> health.AccessRequest
	35, // 8: health.ListAuthorizedTicketsResponse.tickets:type_name -> health.AuthTicket
	3,  // 9: health.HealthAnalysisResponse.user_analysis:type_name -> health.UserHealthAnalysisResponse
	5,  // 10: health.HealthAnalysisResponse.insurer_analysis:type_name -> health.InsurerHealthAnalysisResponse
	1,  // 11: health.HealthService.AnalyzeHealthReportForUser:input_type -> health.AnalyzeHealthReportRequest
	1,  // 12: health.HealthService.AnalyzeHealthReportForInsurer:input_type -> health.AnalyzeHealthReportRequest
	37, // 13: health.HealthService.GetHealthAnalysis:input_type -> health.AnalyzeReportRequest
	6,  // 14: health.HealthService.UploadReport:input_type -> health.UploadReportRequest
	11, // 15: health.HealthService.Login:input_type -> health.LoginRequest
	13, // 16: health.HealthService.RegisterUser:input_type -> health.RegisterUserRequest
	14, // 17: health.HealthService.RegisterInsurer:input_type -> health.RegisterInsurerRequest
	39, // 18: health.HealthService.ListMyReportMeta:input_type -> google.protobuf.Empty
	8,  // 19: health.HealthService.ReadMyReport:input_type -> health.ReadMyReportRequest
	39, // 20: health.HealthService.ListMyAuthorizedTickets:input_type -> google.protobuf.Empty
	18, // 21: health.HealthService.RequestAccess:input_type -> health.RequestAccessRequest
	39, // 22: health.HealthService.ListAccessRequests:input_type -> google.protobuf.Empty
	22, // 23: health.HealthService.ApproveAccessRequest:input_type -> health.ApproveAccessRequestRequest
	24, // 24: health.HealthService.RejectAccessRequest:input_type -> health.RejectAccessRequestRequest
	39, // 25: health.HealthService.ListAuthorizedReports:input_type -> google.protobuf.Empty
	29, // 26: health.HealthService.ListReportMetaByPatientID:input_type -> health.PatientIDRequest
	32, // 27: health.HealthService.ViewAuthorizedReport:input_type -> health.ViewAuthorizedReportRequest
	39, // 28: health.HealthService.ListMyAccessRequests:input_type -> google.protobuf.Empty
	3,  // 29: health.HealthService.AnalyzeHealthReportForUser:output_type -> health.UserHealthAnalysisResponse
	5,  // 30: health.HealthService.AnalyzeHealthReportForInsurer:output_type -> health.InsurerHealthAnalysisResponse
	38, // 31: health.HealthService.GetHealthAnalysis:output_type -> health.HealthAnalysisResponse
	7,  // 32: health.HealthService.UploadReport:output_type -> health.UploadReportResponse
	12, // 33: health.HealthService.Login:output_type -> health.LoginResponse
	15, // 34: health.HealthService.RegisterUser:output_type -> health.RegisterResponse
	15, // 35: health.HealthService.RegisterInsurer:output_type -> health.RegisterResponse
	10, // 36: health.HealthService.ListMyReportMeta:output_type -> health.ListMyReportMetaResponse
	9,  // 37: health.HealthService.ReadMyReport:output_type -> health.ReadMyReportResponse
	36, // 38: health.HealthService.ListMyAuthorizedTickets:output_type -> health.ListAuthorizedTicketsResponse
	19, // 39: health.HealthService.RequestAccess:output_type -> health.RequestAccessResponse
	21, // 40: health.HealthService.ListAccessRequests:output_type -> health.ListAccessRequestsResponse
	23, // 41: health.HealthService.ApproveAccessRequest:output_type -> health.ApproveAccessRequestResponse
	25, // 42: health.HealthService.RejectAccessRequest:output_type -> health.RejectAccessRequestResponse
	28, // 43: health.HealthService.ListAuthorizedReports:output_type -> health.ListAuthorizedReportsResponse
	31, // 44: health.HealthService.ListReportMetaByPatientID:output_type -> health.ListReportMetaResponse
	33, // 45: health.HealthService.ViewAuthorizedReport:output_type -> health.ViewAuthorizedReportResponse
	34, // 46: health.HealthService.ListMyAccessRequests:output_type -> health.ListMyAccessRequestsResponse
	29, // [29:47] is the sub-list for method output_type
	11, // [11:29] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_data_proto_init() }
func file_proto_data_proto_init() {
	if File_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_proto_goTypes,
		DependencyIndexes: file_proto_data_proto_depIdxs,
		EnumInfos:         file_proto_data_proto_enumTypes,
		MessageInfos:      file_proto_data_proto_msgTypes,
	}.Build()
	File_proto_data_proto = out.File
	file_proto_data_proto_goTypes = nil
	file_proto_data_proto_depIdxs = nil
}
